# Generated by Django 5.1.4 on 2024-12-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Formateur'), (2, 'Conseiller'), (3, 'Directeur'), (4, 'Coordinateur'), (5, 'RS'), (6, 'RAF'), (7, 'FC'), (8, 'TPRO'), (9, 'Entreprise'), (10, 'Dregional'), (11, 'Visiteur'), (12, 'Apprentis')], null=True),
        ),
    ]
