# Generated by Django 5.1.3 on 2024-12-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0003_rename_libelle_role_nom'),
        ('utilisateurs', '0005_customuser_centre_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='param.centre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='param.role'),
        ),
    ]
