# Generated by Django 5.1.3 on 2024-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_rename_userprofile_customuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
