# Generated by Django 5.1.3 on 2024-12-16 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_customuserprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuserprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='PHOTO',
            field=models.ImageField(blank=True, default='utilisateurs/imgavatar/default.jpg', null=True, upload_to='utilisateurs/imgavatar'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
