# Generated by Django 5.1.3 on 2024-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_remove_customuserprofile_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
