# Generated by Django 5.1.3 on 2024-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_alter_customuserprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='PHOTO',
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/imgavatar'),
        ),
    ]
