# Generated by Django 5.1.3 on 2024-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_remove_customuserprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/imgavatar/'),
        ),
    ]
