# Generated by Django 5.1.3 on 2024-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0002_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='libelle',
            new_name='nom',
        ),
    ]
